
-- Create a table for private content
create table private_content (
  id bigint generated by default as identity primary key,
  tmdb_id text, 
  title text not null,
  overview text,
  poster_path text,
  backdrop_path text,
  video_url text not null, 
  media_type text default 'movie',
  play_type text default 'direct', -- 'direct', 'embed', 'youtube'
  trailer_url text,
  trailer_urls text[], -- Array of YouTube/MP4 URLs
  logo_path text,
  cast_members text[],
  badges text[], -- Array of badge strings (HD, CC, Dolby Vision, etc.)
  year int,
  allowed_emails text[], -- Array of email strings
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Admin allowlist used by RLS. Keep this in the database, not only in client JS.
create table app_admins (
  email text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

insert into app_admins (email)
values ('methsithc7@gmail.com')
on conflict (email) do nothing;

-- Enable RLS
alter table private_content enable row level security;
alter table app_admins enable row level security;

-- Policy: Users can see content if their email is in the allowed list
create policy "Users can view private content if allowed"
  on private_content for select
  using (
    auth.jwt() ->> 'email' = any(allowed_emails)
  );

create policy "Admins can view admin allowlist"
  on app_admins for select
  using (auth.jwt() ->> 'email' = email);

-- Policy: Only database allowlisted admins can manage private content.
-- Client-side admin checks are UX only; this policy is the actual authorization boundary.
create policy "Admin users can manage private content"
  on private_content
  for all
  using (
    exists (
      select 1 from app_admins
      where app_admins.email = auth.jwt() ->> 'email'
    )
  )
  with check (
    exists (
      select 1 from app_admins
      where app_admins.email = auth.jwt() ->> 'email'
    )
  );
