
-- Create a table for private content
create table private_content (
  id bigint generated by default as identity primary key,
  tmdb_id text, 
  title text not null,
  overview text,
  poster_path text,
  backdrop_path text,
  video_url text not null, 
  media_type text default 'movie',
  play_type text default 'direct', -- 'direct', 'embed', 'youtube'
  trailer_url text,
  trailer_urls text[], -- Array of YouTube/MP4 URLs
  logo_path text,
  cast_members text[],
  badges text[], -- Array of badge strings (HD, CC, Dolby Vision, etc.)
  year int,
  allowed_emails text[], -- Array of email strings
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table private_content enable row level security;

-- Policy: Users can see content if their email is in the allowed list
create policy "Users can view private content if allowed"
  on private_content for select
  using (
    auth.jwt() ->> 'email' = any(allowed_emails)
  );

-- Policy: Allow all authenticated users to insert/update/delete (Protected by UI Logic for now)
-- ideally restricted to specific admin UUIDs
create policy "Authenticated users can manage private content"
  on private_content
  using ( auth.role() = 'authenticated' )
  with check ( auth.role() = 'authenticated' );
