-- Create a table for user library (Watch Later, Continue Watching, etc.)
create table user_library (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  item_id text not null,
  type text not null, -- 'watch_later', 'continue_watching'
  data jsonb not null, -- Stores the movie/show details
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, item_id, type)
);

-- Set up Row Level Security (RLS)
alter table user_library enable row level security;

create policy "Users can view their own library items."
  on user_library for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own library items."
  on user_library for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own library items."
  on user_library for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own library items."
  on user_library for delete
  using ( auth.uid() = user_id );

-- Create a table for public profiles (optional, but good for avatar/username)
-- Note: Supabase handles basic user metadata in auth.users, but a separate table is often used.
-- For this implementation, we are using auth.users metadata directly for simplicity, 
-- but if you want to query other users' profiles, you'd need this table.
-- We will skip creating a separate profiles table for now as we store username/avatar in user_metadata.
